### ISSUE TITLE
Existe una posible refactorización

### ISSUE THREAD

**Issue by gaal1le0** [ismabk/Ejercicios-de-arrays-Avanzado#1]
https://github.com/ismabk/Ejercicios-de-arrays-Avanzado/blob/c0b830c89d78d631dd3bd501b1c22863312787f5/assets/scripts/index.js#L154

Si observas el código de los 3 if y de las sentencias del interior se pueden refactorizar de la siguiente manera:

```js
        //esta comprobación la haces en la funcion compare value y devuleves un string que es el que le haras el console log fuera de la funcion, reciuerda que tu funcion es solo responsable de una cosa.
        res[1]==='true' ? console.log('Distinto tamaño y mismo contenido') : console.log(`Distinto tamaño y mismo contenido hasta ${res[0].length}`)
            return compareValue(array2,array1)
```

Si haces ese cambio tu código estará más refactorizado y seguira el primer principio solid de responsabilidad unica.

**Comment by ismabk** [comment]
queda refactorizado el código, te pongo el enlace al repo 
https://github.com/ismabk/Ejercicios-de-arrays-Avanzado
