### ISSUE TITLE
No veo la factorización que te indique

### ISSUE THREAD

**Issue by gaal1le0** [ismabk/Ejercicios-de-arrays-Avanzado#3]
https://github.com/ismabk/Ejercicios-de-arrays-Avanzado/blob/0503192e61ba4d5f6fcd93343d114adb897dd33c/assets/scripts/index.js#L154

Si observas el código de los 3 if y de las sentencias del interior se pueden refactorizar de la siguiente manera:

```js
        //esta comprobación la haces en la funcion compare value y devuleves un string que es el que le haras el console log fuera de la funcion, reciuerda que tu funcion es solo responsable de una cosa.
        res[1]==='true' ? console.log('Distinto tamaño y mismo contenido') : console.log(`Distinto tamaño y mismo contenido hasta ${res[0].length}`)
            return compareValue(array2,array1)
```

No veo la factorización que te indique

**Comment by ismabk** [comment]
queda resuelta la refactorización, te lo subo a breathcode

**Comment by gaal1le0** [comment]
Perfecto!!
